services:
  rag-fastapi:
    init: true
    image: nithish1/rag:fastapi-arm64-3.0.2
    container_name: rag-fastapi
    restart: unless-stopped
    networks:
      - rag-net
    ports:
      - "9001:9000"
    env_file:
      - rag.env
    environment:
      UVICORN_WORKERS: 1

    depends_on:
      qdrant:
        condition: service_started
      redis:
        condition: service_healthy
      mis-dense-nomic-text:
        condition: service_healthy
      mis-jina-embeddings-v2-base-code:
        condition: service_healthy
      mis-sparse-splade-pp:
        condition: service_healthy
      mis-reranker-jina:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - shared_uploads:/shared/uploads

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - rag-net
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  flower:
    image: mher/flower:2.0
    container_name: flower
    restart: unless-stopped
    networks:
      - rag-net
    ports:
      - "5555:5555"
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    depends_on:
      redis:
        condition: service_healthy

  qdrant:
    init: true
    image: qdrant/qdrant:v1.17
    container_name: qdrant
    restart: unless-stopped
    networks:
      - rag-net
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT_ALLOW_UNSAFE_FS=true
      - QDRANT__CONFIG=config/production.yml
    volumes:
      - ./qdrant_data:/qdrant/storage
      - ./qdrant_config.yml:/qdrant/config/production.yml

  mis-jina-embeddings-v2-base-code:
    init: true
    image: nithish1/mis:jina-embeddings-v2-base-code-arm64-1.2.0
    container_name: mis-jina-embeddings-v2-base-code
    ports:
      - "8001:8000"
    restart: unless-stopped
    networks:
      - rag-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 600s
  
  mis-dense-nomic-text:
    init: true
    image: nithish1/mis:dense-nomic-text-arm64-1.2.0
    container_name: mis-dense-nomic-text
    ports:
      - "8002:8000"
    restart: unless-stopped
    networks:
      - rag-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 600s

  mis-sparse-splade-pp:
    init: true
    image: nithish1/mis:sparse-splade-pp-arm64-1.2.0
    container_name: mis-sparse-splade-pp
    ports:
      - "8003:8000"
    restart: unless-stopped
    networks:
      - rag-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 600s

  mis-reranker-jina:
    init: true
    image: nithish1/mis:reranker-jina-arm64-1.2.0
    container_name: mis-reranker-jina
    ports:
      - "8004:8000"
    restart: unless-stopped
    networks:
      - rag-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 600s

  chunk-worker:
    init: true
    image: nithish1/rag:fastapi-arm64-3.0.2
    restart: unless-stopped
    networks:
      - rag-net
    healthcheck:
      disable: true
    command: >
      celery -A workers.ingest_worker worker
      --queues workspace_chunk,enterprise_chunk
      --concurrency 1
      --max-tasks-per-child 200
      --loglevel info
    env_file:
      - rag.env

    depends_on:
      redis:
        condition: service_healthy

    deploy:
      replicas: 1

    volumes:
      - shared_uploads:/shared/uploads
      - chunk_store:/data/chunks
  
  embed-worker:
    init: true
    image: nithish1/rag:fastapi-arm64-3.0.2
    restart: unless-stopped
    networks:
      - rag-net
    healthcheck:
      disable: true
    command: >
      celery -A workers.ingest_worker worker
      --queues workspace_embed,enterprise_embed
      --concurrency 1
      --max-tasks-per-child 200
      --loglevel info

    env_file:
      - rag.env

    depends_on:
      redis:
        condition: service_healthy
      mis-dense-nomic-text:
        condition: service_healthy
      mis-jina-embeddings-v2-base-code:
        condition: service_healthy
      mis-sparse-splade-pp:
        condition: service_healthy
      mis-reranker-jina:
        condition: service_healthy
    
    deploy:
      replicas: 1

    volumes:
      - chunk_store:/data/chunks

  dbwrite-worker:
    init: true
    image: nithish1/rag:fastapi-arm64-3.0.2
    restart: unless-stopped
    networks:
      - rag-net
    healthcheck:
      disable: true
    command: >
      celery -A workers.ingest_worker worker
      --queues workspace_dbwrite,enterprise_dbwrite
      --concurrency 1
      --max-tasks-per-child 200
      --loglevel info
    env_file:
      - rag.env

    depends_on:
      redis:
        condition: service_healthy
      qdrant:
        condition: service_started
      
    deploy:
      replicas: 1

    volumes:
      - chunk_store:/data/chunks

networks:
  rag-net:
    driver: bridge

volumes:
  shared_uploads:
  redis_data:
  chunk_store:
