services:
  qdrant:
    init: true
    image: qdrant/qdrant:v1.17.0
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT_ALLOW_UNSAFE_FS=true
      - QDRANT__CONFIG=config/production.yml
    volumes:
      - ./qdrant_data:/qdrant/storage
      - ./qdrant_config.yml:/qdrant/config/production.yml
